---
title: "Untitled"
author: "李靜怡"
date: "9/25/2019"
---

```{r}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext); library(magrittr)

font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```

```{r}
library(readr)
df_taoyuanMarriage <- read_csv("https://data.tycg.gov.tw/opendata/datalist/datasetMeta/download?id=f95d1a33-ec56-44c5-a9ec-3afba8157e39&rid=fd2070ef-7431-4f9c-bc3a-82d7bfbcd2fb")
```

```{r}
df_taoyuanMarriage %>%
  gather(
    grep("月$",colnames(.)),
    key = "年份", value = "對數"
  ) -> b
```

```{r}
download_id_64a896aa_a6aa_4362_90fb_4270d90ff625_rid_85e11adb_c228_4b57_a7fd_1d99fb31129c <- read_csv("https://data.tycg.gov.tw/opendata/datalist/datasetMeta/download?id=64a896aa-a6aa-4362-90fb-4270d90ff625&rid=85e11adb-c228-4b57-a7fd-1d99fb31129c")
```

```{r}
library(readr)
subsetDataTWbank <- read_csv("https://www.dropbox.com/s/t8ulj3d7cgl8jh5/subsetDataTWbank.csv?dl=1")
```

```{r}
library(ggplot2)
ggplot(subsetDataTWbank)+
  geom_point(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
  ) +
  geom_line(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
  ) 

subsetDataTWbank %>%
  gather(
    `定存利率-一個月-固定`,`定存利率-二年期-固定`,`定存利率-三年期-固定`,
    key = "期數", value = "利率"
  ) %>%
  ggplot() +
  geom_line(
    aes(x=西元年月,y=利率)
  )
```

```{r}
twCalendar <- c("民國88年11月1日","民國88年12月1日","民國89年1月1日")

twCalendar %>%
  str_extract_all("[:digit:]+") %>%
  # 將每個日期的「年」數字加上1991再合併年月日成為`yyyy-mm-dd`格式
  purrr::map_chr(
             function(x) {
               x1=as.integer(x[[1]])+1911
               x[[1]]=as.character(x1)
               stringr::str_c(x,collapse="-")
             }
             ) -> westernCalendar
```

```{r}
library(grDevices) # 不同顏色模型代碼的呈現及轉換
library(scales) # show_col()螢幕立即顯示顏色
library(colorspace) # 調色盤選擇及ggplot應用工具
library(shinyjs) # 支援套件
library(dplyr)
```

```{r}
show_col(
  c(hsv(0/360,0.3,0.9),hsv(165/360,0.3,0.9),hsv(165/360,0.3,0.9),hsv(165/360,0.3,0.9),hsv(0/360,0.3,0.9),
    hsv(0/360,0.3,0.9),hsv(165/360,0.3,0.9),hsv(165/360,0.3,0.9),hsv(165/360,0.3,0.9),hsv(0/360,0.3,0.9),
    hsv(165/360,0.3,0.9),hsv(30/360,0.13,0.9),hsv(165/360,0.3,0.9),hsv(30/360,0.13,0.9),hsv(165/360,0.3,0.9),
    hsv(30/360,0.13,0.9),hsv(170/360,0.5,0.6),hsv(30/360,0.13,0.9),hsv(170/360,0.5,0.6),hsv(30/360,0.13,0.9),
    hsv(30/360,0.13,0.9),hsv(30/360,0.13,0.9),hsv(30/360,0.13,0.9),hsv(30/360,0.13,0.9),hsv(30/360,0.13,0.9))
)

colors()
```

```{r}
library(shiny)
library(colorspace)
choose_color()
```

```{r}
choose_palette(gui="shiny")

sequential_hcl(n = 5, h = c(261, 200), c = c(60, NA, 0), l = c(25, 95), power = c(0.7, 1.3), register = "myPalette") -> a
show_col(a)
```

```{r}
pal_qual <- colorspace::qualitative_hcl(
  n = 7, 
  h = c(100, 180), c = 45, l = 80, 
  register = "myQualitative"
  )
pal_qual %>% specplot(hcl=F)
```

```{r}
data.frame(
  x1 = factor(sample(c(1L,2L,3L),100,replace=T)),
  x2 = runif(100),
  y = runif(100),
  z1 = rnorm(100),
  z2 = factor(sample(letters[1:4],100,replace=T))
) -> df_example

library(ggplot2)

df_example %>%
  ggplot()+
  geom_boxplot(
    aes(x=x1,y=y,fill=z2)
  ) -> basicBoxplot
basicBoxplot


sequential_hcl(n = 5, h = c(261, 200), c = c(60, NA, 0), l = c(25, 95), power = c(0.7, 1.3),palette = "myPalette",register = "myPalette")
show_col(b)

basicBoxplot +
  scale_fill_brewer(palette="myPalette") # 由於色圈會由0度出發回到360度所以第1個及第5個會是同色，因此4類要創出5個顏色才不會有1,4類同色問題。


basicBoxplot +
  scale_fill_discrete_qualitative()
```

```{r}
library(readr)
disposableIncome <- read_csv("https://www.dropbox.com/s/z80sbjw94cjex8x/disposableIncome.csv?dl=1",
locale = locale(encoding = "BIG5"), skip = 4)
```

```{r}
library(dplyr)
library(tidyr)
colnames(disposableIncome)[[1]] <- "年份"

disposableIncome %>%
  .[-c(44:49),] -> disposableIncome

as.numeric(disposableIncome$年份) -> 
  disposableIncome$年份

disposableIncome %>%
  filter(年份 >= 2003) %>%
  gather(
    -1,
    key = "組別", value = "元"
  ) %>%
  ggplot() +
  geom_line(
    aes(x=年份, y=元, color = 組別)
  )
```

```{r}
load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/graphData_homework2019-10-08_014.Rda?raw=true"))

c('年分','地區','來台旅遊人數(萬)') -> names(graphData$travelerFromAsia)

graphData$travelerFromAsia
```

```{r, fig.showtext=TRUE, message=FALSE}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext)
font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())

as.numeric(graphData$travelerFromAsia$年分) -> 
  graphData$travelerFromAsia$年分

graphData$travelerFromAsia %>%
  ggplot() +
  geom_line(
    aes(x = 年分, y = `來台旅遊人數(萬)`, color = 地區)
  ) 
```

```{r}
dataCPI <- read_csv("https://www.dropbox.com/s/ov2bvef5o3apei0/PR0101A2Mc.csv?dl=1")

## 改變數名稱
dataCPI %>% 
  dplyr::rename(
    年月=X1,
    CPI=原始值
  ) -> dataCPI

# 移除「有NA」的row
dataCPI %>% na.omit() -> dataCPI

## 調整class
dataCPI$年月 %>% str_c("/01") %>% #擴增為YMD表示
  ymd() -> dataCPI$年月

# 改成2003M1為基期,其指數為100
dataCPI %>% filter(年月==ymd("2003-01-01")) %>% 
  select(CPI) -> CPI2003M1
dataCPI %>% 
  mutate(CPI=CPI/CPI2003M1$CPI*100) -> dataCPI2
```

```{r}
dataCPI2 %>% ggplot()+
  geom_line(aes(x=年月,y=CPI)) -> basePlot2
basePlot2

breakDates <- c("2003-01-01",
                "2005-01-01","2010-01-01","2015-01-01",
                "2018-01-01")
breakDates %>% ymd() -> breakDates

breakLabels <- c("2003",
                 "2005","2010","2015",
                 "2018")
basePlot2 +
  scale_x_date(limits=c(ymd("2003-01-01"),NA),
               breaks = breakDates,
               labels = breakLabels)

basePlot2 +
  scale_x_date(limits=c(ymd("2003-01-01"),NA),
               breaks = breakDates,
               labels = year(breakDates)-1911)
```

```{r}
basePlot2 +
  scale_x_date(limits=c(ymd("2003-01-01"),NA),
               breaks = breakDates,
               labels = year(breakDates)-1911)
```

```{r}
library(readr)
startSalaryTopCat<- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/startSalaryTopCat.csv")

startSalaryTopCat$大職業別[2:7] %>% str_c(.,collapse="','")

startSalaryTopCat %>% filter(
  大職業別 %in% c('工業部門','礦業及土石採取業','製造業','電力及燃氣供應業','用水供應及污染整治業','營造業')
) -> startingSalary_industrial

graphList <- list()

startingSalary_industrial %>%
  filter(大職業別 !='工業部門') -> startingSalary_industrial_sub
startingSalary_industrial_sub %>%  
  ggplot(aes(x=大職業別))+
  geom_col(aes(y=`經常性薪資-薪資`))-> graphList$經常薪資_col0

graphList$經常薪資_col0

startingSalary_industrial_sub %>%
  mutate(
    大職業別ordered=reorder(大職業別,
                    `經常性薪資-薪資`,order=T) # order=T才會輸出成ordered factor
  ) -> startingSalary_industrial_sub

startingSalary_industrial_sub %>%
  ggplot()+
  geom_col(
    aes(x=reorder(大職業別,`經常性薪資-薪資`,order = T),y=`經常性薪資-薪資`),
    fill = "#5A99B3",
    width = 0.4
  ) +
  theme(
    aspect.ratio = 1/1.2
  ) +
  geom_text(
    aes(
      x = reorder(大職業別,`經常性薪資-薪資`,order = T),
      y = `經常性薪資-薪資`,
      label = `經常性薪資-薪資`
    ),
    nudge_y = -2000,
    color = "white"
  ) +
  coord_flip() +
  labs(
    x = "大職業別"
  ) -> graphList$經常薪資_x有排序ed_col1

graphList$經常薪資_x有排序ed_col1
```

```{r}
load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/homework2/graphData_homework2_005.Rda?raw=true"))
```

```{r}
graphData$data %>%
  ggplot(aes(x=年份,y=毛額,color=國民所得_儲蓄_投資毛額))+
  geom_line(aes(linetype=國民所得_儲蓄_投資毛額,size=國民所得_儲蓄_投資毛額))+
  
  scale_linetype_manual(
    values = c("85","12","31"),
    breaks = c(
    "1.4國民所得毛額GNI:1.1+1.2+1.3","3.3國民儲蓄毛額 :2.1+3.2","3.5國內投資毛額"),
    labels = c("所得毛額","儲蓄毛額","投資毛額")
    )+
  theme(legend.position = "none")+
  scale_size_manual(values = c(1,0.5,0.2))+
  
  annotate("text", x = 2016, y = 155000, 
           label = paste("國民所得毛額"), size = 3)+
  annotate("text", x = 2016, y = 70000, 
           label = paste("國民儲蓄毛額"), size = 3) +
  annotate("text", x = 2016, y = 42000, 
           label = paste("國民投資毛額"), size = 3) +
  labs(title = "國民所得、儲蓄、投資毛額",
       caption = "資料來源: 中華民國統計資料網",
       subtitle = "單位:億(新台幣)") +
  geom_rect(
    xmin = c(2008),
    xmax = c(2009),
    ymin = -Inf,
    ymax = Inf,
    alpha = 0.01,
    color = "gray"
  )
```

```{r}
set.seed(2019)
x <- rnorm(100)
head(x)

ggplot2::cut_interval(x,n=8) -> x_interval
levels(x_interval)

df_x <- data.frame(
  x=x,
  x_interval=x_interval
)

df_x %>%
  group_by(x_interval) %>%
  summarise(
    interval_count=n()
  ) %>%
  ungroup() %>% #View
  ggplot(aes(x=x_interval))+
  geom_col(
    aes(y=interval_count)
  )

df_x %>%
  ggplot(aes(x=x))+
  geom_histogram(bins=8)
```

```{r}
df_position <- data.frame(
  x=rep(c("a","b"), each=3),
  y=c(3,1,3,8,6,10)
)

graphList <- list()

df_position %>%
  ggplot(aes(x=x,y=y))+
  geom_point(
    color="#5A99B3"
  ) + 
  scale_y_continuous(
    breaks=c(1,3,6,8,10)
  )+
  annotate(
    geom="text",
    x=1.1, y=3, label="x 2" # 利用factor的type為integer的特質設x位置
  )+
  labs(
    title="Position identity",
    subtitle="Position沒有調整"
    ) -> graphList$position_none

graphList$position_none

df_position %>%
  ggplot(aes(x=x,y=y,color=y))+
  geom_point(
    position="stack", color="#5A99B3"
  )+
  labs(
    title= "Position stack",
    subtitle = "各x類y值疊加上去" 
  )-> graphList$position_stack

ggpubr::ggarrange(
  graphList$position_none,
  graphList$position_stack
)
```

```{r}
library(readr)
df_geo_northTW <- read_csv("https://www.dropbox.com/s/6uljw24zkyj7avs/df_geo_northTW.csv?dl=1")
```

```{r}
ggplot()+theme_linedraw()+
  scale_x_continuous(limits=c(120,123),breaks=120:123,
                     expand=expand_scale(add=c(0,0)))+
  scale_y_continuous(limits=c(24,26),breaks=24:26,
                     expand=expand_scale(mult = c(0,0))) ->
  myGrids

myGrids

df_geo_northTW %>%
  filter(
    COUNTYNAME == c("新北市","臺北市")
  ) %>%
  ggplot(
    aes(
      x=x, y=y
    )
  ) +
  geom_polygon() +
  theme_linedraw()+
  geom_path(
    data=data.frame(
      x=c(121.55,121.7,121.9),
      y=c(25.1,24.7,24.7)
      ),
    aes(x=x,y=y)
    ) +
  annotate(
    "text",
    x=121.9,y=24.71,label="這是臺北市",
    vjust=0
  ) -> list_graphs$northTW
  
  
```

```{r}
library(magick)
image_read("https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/2450df20386177.562ea7d13f396.jpg") -> taipei101

taipei101 %>%
  image_info() -> taipei101_info

list_graphs <- list()

theme_linedraw()+
  theme(
    panel.background = element_rect(fill="cyan4")
  ) -> list_graphs$theme_backgroundCheck

# 圖片底色非透明
taipei101 %>%
  image_ggplot()+
  list_graphs$theme_backgroundCheck

image_fill(
  taipei101, "transparent", point = "+100+100", fuzz = 30
  ) %>% # fuzz=對邊界定義模糊度 %>%
    image_ggplot()+list_graphs$theme_backgroundCheck

image_fill(taipei101,"transparent", point = "+100+100", fuzz=30) -> 
  taipei101transparent

##transparent = 去背透明圖層

taipei101transparent %>%
  as.raster() ->
  raster_taipei101

##raster = rgb矩陣

loc <- c(lon=121.5622782,lat=25.0339687) # Taipei101 經緯度
imgWidth <- 0.13 # Taipei101在圖片佔寬
# 檢視圖片高寬比
taipei101_info$height/taipei101_info$width -> img_asp

list_graphs$northTW +
  annotation_raster(raster_taipei101,
                    loc[1]-imgWidth/2,loc[1]+imgWidth/2,
                    loc[2]-imgWidth/2*img_asp,
                    loc[2]+imgWidth/2*img_asp)

```

```{r}
colnames(transcript100to106withLocation) %<>% 
  `Encoding<-`("UTF-8")

grade %>%
  .[.$學號=="410078054",] %>%
  rbind(
    grade[grade$學號 == "410073060",]
  ) %>%
  rbind(
    grade[grade$學號 == "410077058",]
  ) %>%
  .[,-c(2:3)] -> gradeData

save(gradeData, file = "gradeData.rda")

names(transcriptList) %<>% `Encoding<-`("UTF-8")
```

```{r}
transcript100to106withLocation %>%
  .[.$`必選修類別（必／選／通）` == "通",] %>%
  rbind(
    transcript100to106withLocation[grepl("體育：",transcript100to106withLocation$科目名稱),]
  ) -> transcript100to106withPEandGeneral

transcript100to106withPEandGeneral[transcript100to106withPEandGeneral$每週 == "一",24] <- 1
transcript100to106withPEandGeneral[transcript100to106withPEandGeneral$每週 == "二",24] <- 2
transcript100to106withPEandGeneral[transcript100to106withPEandGeneral$每週 == "三",24] <- 3
transcript100to106withPEandGeneral[transcript100to106withPEandGeneral$每週 == "四",24] <- 4
transcript100to106withPEandGeneral[transcript100to106withPEandGeneral$每週 == "五",24] <- 5

as.numeric(str_sub(transcript100to106withPEandGeneral$每週時間,1,1)) -> transcript100to106withPEandGeneral$開始
as.numeric(str_sub(transcript100to106withPEandGeneral$每週時間,-1,-1)) -> transcript100to106withPEandGeneral$結束



transcript100to106withPEandGeneral %>%
  filter(
    學年 == 103, 學屆 == 103,
    `必選修類別（必／選／通）` == "必",
    學系 == "經濟學系"
  ) %>% 
  ggplot(aes(x=每週,y=開始)) +
  geom_tile(
    alpha = 0.1
  ) +
  scale_y_continuous(
    trans = "reverse"
  )
```

```{r}
graphListD$myGrade %>% 
  ggplot() + 
  geom_bar(
    mapping = aes(
      x = 學年期, 
      y = 總修學分
    ), 
    stat = "identity", 
    width = 0.6, 
    fill = "#AAAAAA"
  ) + 
  geom_bar(
    mapping = aes(
      x = 學年期, 
      y = 實得學分, 
      fill = 學位
    ), 
    stat = "identity", 
    width = 0.6
  ) -> 
  graphListP$myCredit_base
qualitative_hcl(n = 2, h = c(-140, 0), c = 100, l = 60, register = "godPalette_2Qua")

graphListP$myCredit_base + 
  scale_fill_discrete_qualitative(palette = "godpalette_2Qua", nmax = 2, rev = F) + 
  #顛倒顏色要在這下
  scale_y_continuous(
    limits = c(0,55), 
    expand = expand_scale(add = c(0, 0))
  ) + 
  theme_bw() -> 
  graphListP$myCredit_1
graphListP$myCredit_1 + 
  geom_path(
    mapping = aes(
      x = 學年期, 
      y = 歷年成績 - 45, 
      group = "a"   #須宣告所有資料為一群
    ), 
    color = "#DCDCDC", 
    size = 2
  ) + 
  geom_point(
    mapping = aes(
      x = 學年期, 
      y = 歷年成績 - 45, 
      color = 學位
    ), 
    size = 2
  ) + 
  geom_text(
    mapping = aes(
      x = 學年期, 
      y = 歷年成績 - 44, 
      label = 歷年成績, 
      color = 學位
    ), 
    vjust = 0, 
    size = 3
  ) + 
  scale_color_discrete_qualitative(palette = "godpalette_2Qua", nmax = 2, rev = F) -> 
  graphListP$myCredit_2
graphListP$myCredit_2 + 
  #調整legend
  theme(
    legend.position = c(0.1, 0.85), 
    legend.background = element_blank(), 
    legend.title = element_blank(), 
    legend.key.size = unit(0.8, "cm")
  ) + 
  #清理輔助線
  theme(
    panel.border = element_blank(), 
    panel.grid.minor = element_blank(), 
    panel.grid.major.x = element_blank()
  ) + 
  #清理格線
  theme(
    axis.title = element_blank(), 
    axis.ticks = element_blank(), 
    axis.text.y = element_blank()
  ) -> 
  graphListP$myCredit_3
graphListP$myCredit_3 + 
  geom_hline(
    yintercept = 0
  ) + 
  geom_hline(
    yintercept = 20, 
    color = "red", 
    linetype = "58"
  ) + 
  geom_hline(
    yintercept = 35, 
    color = "red", 
    linetype = "58"
  ) + 
  annotate(
    "text", x = "大一上", y = 21, 
    label = "20學分", 
    color = "red", 
    hjust = 0.6, 
    vjust = 0
  ) + 
  annotate(
    "text", x = "碩一下", y = 36, 
    label = "80分", 
    color = "red", 
    hjust = 0, 
    vjust = 0
  ) -> 
  graphListP$myCredit_4
graphListP$myCredit_4 + 
  labs(
    title = "歷年學業表現", 
    subtitle = "學分數與成績趨勢"
  ) + 
  theme(
    plot.title = element_text(hjust = 0.5, size = 20), 
    plot.subtitle = element_text(hjust = 0.5, color = "#888888"), 
    aspect.ratio = 1/1.414, 
    axis.text.x = element_text(color = "black")
  ) -> 
  graphListP$mycredit_end
```

```{r}
library(sf)

outer <-     
  rbind( # 外圍
    c(1,5),
    c(2,1),
    c(5,1),
    c(5,5),
    c(1,5)) # 必需自行輸入起點close it

hole <-
  rbind( # 洞
    c(2,4),
    c(3,2),
    c(4,3),
    c(2,4))  # 必需自行輸入起點close it
  
poly <- st_polygon(
  list(
    outer, 
    hole
  )
) 

poly %>% ggplot()+geom_sf()


outer2 <- outer + 12
hole2 <- hole + 12

mpoly <- st_multipolygon(
  list(
    list(
      outer,
      hole
    ),
    list(
      outer2,
      hole2
    )
  )
) 

mpoly %>% ggplot()+geom_sf()


mline <- st_multilinestring(
  list(
    rbind(
      c(1,0),
      c(2,3),
      c(-1,3)),
    rbind(
      c(-2,3),
      c(-1,-1))
    )
  )

mline %>% ggplot()+geom_sf()


st_geometrycollection(
  list(
    mline,
    poly, mpoly
  )
) %>% ggplot()+ geom_sf()
```

```{r}
sfg_county1 <- st_polygon(list(
  outer,hole
))
sfg_county2 <- st_polygon(list(
  outer2, hole2
))

sfc_county12column <- st_sfc(sfg_county1,sfg_county2)

sfc_county12column %>% ggplot+geom_sf()


sfc_county12column %>%
  st_set_crs(4326) -> # EPSG: 4326
  sfc_county12column

df_county12 <- data.frame(
  name=c("county1","county2"),
  population=c(100,107)
)

df_county12 %>%
  st_set_geometry(sfc_county12column) -> df_county12

df_county12 %>% names

dir.create("county12")
write_sf(df_county12,"county12/county12.shp")
```

